# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('codigo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('tipocodigo', models.CharField(max_length=1, null=True)),
                ('localizacion', models.CharField(max_length=30, null=True)),
                ('existenciamax', models.CharField(max_length=30, null=True)),
                ('referecia', models.CharField(max_length=30, null=True)),
                ('dependencia', models.CharField(max_length=30, null=True)),
                ('existenciamin', models.CharField(max_length=30, null=True)),
                ('descripcionapida', models.CharField(max_length=30, null=True)),
                ('estado', models.CharField(max_length=30, null=True)),
                ('fletes', models.CharField(max_length=30, null=True)),
                ('costoventa', models.CharField(max_length=30, null=True)),
                ('costobase', models.CharField(max_length=30, null=True)),
                ('tipoarticulo', models.CharField(max_length=30, null=True)),
                ('preciovent1', models.CharField(max_length=30, null=True)),
                ('tipoempaque', models.CharField(max_length=30, null=True)),
                ('preciovent2', models.CharField(max_length=30, null=True)),
                ('preciovent3', models.CharField(max_length=30, null=True)),
                ('dtofacturacion', models.CharField(max_length=30, null=True)),
                ('lote', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
